// Define Every Possible Landmark
const landmarks = [
	{id: 0, name: 'Eiffel Tower', country: 'France', continent: 'Europe'},
	{id: 1, name: 'Colosseum', country: 'Italy', continent: 'Europe'},
	{id: 2, name: 'Big Ben', country: 'United Kingdom', continent: 'Europe'},
	{id: 3, name: 'Sagrada Familia', country: 'Spain', continent: 'Europe'},
	{id: 4, name: 'The Louvre', country: 'France', continent: 'Europe'},
	{id: 5, name: 'The Acropolis', country: 'Greece', continent: 'Europe'},
	{id: 6, name: 'Neuschwanstein Castle', country: 'Germany', continent: 'Europe'},
	{id: 7, name: 'Hermitage Museum', country: 'Russia', continent: 'Europe'},
	{id: 8, name: 'The Vatican', country: 'Italy', continent: 'Europe'},
	{id: 9, name: 'Buckingham Palace', country: 'United Kingdom', continent: 'Europe'},
	{id: 10, name: 'Stonehenge', country: 'United Kingdom', continent: 'Europe'},
	{id: 11, name: 'Brandenburg Gate', country: 'Germany', continent: 'Europe'},
	{id: 12, name: 'ISS', country: 'Space', continent: 'The final frontier'},
	{id: 13, name: 'The Parthenon', country: 'Greece', continent: 'Europe'},
	{id: 14, name: 'Tower Bridge', country: 'United Kingdom', continent: 'Europe'},
	{id: 15, name: 'The Palace of Versailles', country: 'France', continent: 'Europe'},
	{id: 16, name: 'Charles Bridge', country: 'Czech Republic', continent: 'Europe'},
	{id: 17, name: 'Mont Saint Michel', country: 'France', continent: 'Europe'},
	{id: 18, name: 'Saint Basil\'s Cathedral', country: 'Russia', continent: 'Europe'},
	{id: 19, name: 'La Rambla', country: 'Spain', continent: 'Europe'},
	{id: 20, name: 'Atomium', country: 'Belgium', continent: 'Europe'},
	{id: 21, name: 'Trevi Fountain', country: 'Italy', continent: 'Europe'},
	{id: 22, name: 'Piazza San Marco in Venice', country: 'Italy', continent: 'Europe'},
	{id: 23, name: 'Edinburgh Castle', country: 'United Kingdom', continent: 'Europe'},
	{id: 24, name: 'Gaudi\'s Park Guell', country: 'Spain', continent: 'Europe'},
	{id: 25, name: 'Berlin Wall', country: 'Germany', continent: 'Europe'},
	{id: 26, name: 'Pantheon in Rome', country: 'Italy', continent: 'Europe'},
	{id: 27, name: 'St Peter\'s Square', country: 'Vatican City', continent: 'Europe'},
	{id: 28, name: 'Palace of Westminster', country: 'United Kingdom', continent: 'Europe'},
	{id: 29, name: 'Tower of Pisa', country: 'Italy', continent: 'Europe'},
	{id: 30, name: 'Rialto Bridge', country: 'Italy', continent: 'Europe'},
	{id: 31, name: 'Arc de Triomphe of Paris', country: 'France', continent: 'Europe'},
	{id: 32, name: 'Royal Palace of Madrid', country: 'Spain', continent: 'Europe'},
	{id: 33, name: 'The Alhambra', country: 'Spain', continent: 'Europe'},
	{id: 34, name: 'The Duomo in Milan', country: 'Italy', continent: 'Europe'},
	{id: 35, name: 'Great Wall of China', country: 'China', continent: 'Asia'},
	{id: 36, name: 'Taj Mahal', country: 'India', continent: 'Asia'},
	{id: 37, name: 'Mount Everest', country: 'Nepal', continent: 'Asia'},
	{id: 38, name: 'Petra', country: 'Jordania', continent: 'Asia'},
	{id: 39, name: 'Burj Khalifa', country: 'UAE', continent: 'Asia'},
	{id: 40, name: 'Angkor Wat', country: 'Cambodia', continent: 'Asia'},
	{id: 41, name: 'Tokyo Tower', country: 'Japan', continent: 'Asia'},
	{id: 42, name: 'Forbidden City', country: 'China', continent: 'Asia'},
	{id: 43, name: 'Batu Caves', country: 'Malaysia', continent: 'Asia'},
	{id: 44, name: 'Merlion', country: 'Singapore', continent: 'Asia'},
	{id: 45, name: 'The Golden Temple', country: 'India', continent: 'Asia'},
	{id: 46, name: 'The Terracotta Army', country: 'China', continent: 'Asia'},
	{id: 47, name: 'Marina Bay Sands', country: 'Singapore', continent: 'Asia'},
	{id: 48, name: 'Borobudur Temple', country: 'Indonesia', continent: 'Asia'},
	{id: 49, name: 'Petronas Twin Towers', country: 'Malaysia', continent: 'Asia'},
	{id: 50, name: 'Leshan Giant Buddha', country: 'China', continent: 'Asia'},
	{id: 51, name: 'Taipei 101', country: 'Taiwan', continent: 'Asia'},
	{id: 52, name: 'The Red Fort', country: 'India', continent: 'Asia'},
	{id: 53, name: 'The Shwedagon Pagoda', country: 'Myanmar', continent: 'Asia'},
	{id: 54, name: 'The Blue Mosque', country: 'Turkey', continent: 'Asia'},
	{id: 55, name: 'Statue of Liberty', country: 'United States', continent: 'North America'},
	{id: 56, name: 'Grand Canyon', country: 'United States', continent: 'North America'},
	{id: 57, name: 'Golden Gate Bridge', country: 'United States', continent: 'North America'},
	{id: 58, name: 'Mount Rushmore', country: 'United States', continent: 'North America'},
	{id: 59, name: 'Empire State Building', country: 'United States', continent: 'North America'},
	{id: 60, name: 'Niagara Falls', country: 'United States', continent: 'North America'},
	{id: 61, name: 'Hollywood Sign', country: 'United States', continent: 'North America'},
	{id: 62, name: 'Blue Hole', country: 'Belize', continent: 'North America'},
	{id: 63, name: 'The Panama Canal', country: 'Panama', continent: 'North America'},
	{id: 64, name: 'Chiczten Izta', country: 'Mexico', continent: 'North America'},
	{id: 65, name: 'CN Tower', country: 'Canada', continent: 'North America'},
	{id: 66, name: 'Christ the Redeemer', country: 'Brazil', continent: 'South America'},
	{id: 67, name: 'Machu Picchu', country: 'Peru', continent: 'South America'},
	{id: 68, name: 'Iguazu Falls', country: 'Argentina', continent: 'South America'},
	{id: 69, name: 'The Galapagos Islands', country: 'Ecuador', continent: 'South America'},
	{id: 70, name: 'Moai Statues', country: 'Chile', continent: 'South America'},
	{id: 71, name: 'Tiwanaku', country: 'Bolivia', continent: 'South America'},
	{id: 72, name: 'Perito Moreno Glacier', country: 'Argentina', continent: 'South America'},
	{id: 73, name: 'Casa Rosada', country: 'Argentina', continent: 'South America'},
	{id: 74, name: 'Valle de la Luna', country: 'Chile', continent: 'South America'},
	{id: 75, name: 'Rainbow Mountain', country: 'Peru', continent: 'South America'},
	{id: 76, name: 'The Amazon Rainforest', country: 'Brazil', continent: 'South America'},
	{id: 77, name: 'The Atacama Desert', country: 'Chile', continent: 'South America'},
	{id: 78, name: 'Salar de Uyuni', country: 'Bolivia', continent: 'South America'},
	{id: 79, name: 'The Cathedral of Quito', country: 'Ecuador', continent: 'South America'},
	{id: 80, name: 'Christ of the Andes', country: 'Argentina', continent: 'South America'},
	{id: 81, name: 'Nazca Lines', country: 'Peru', continent: 'South America'},
	{id: 82, name: 'Pyramids of Giza', country: 'Egypt', continent: 'Africa'},
	{id: 83, name: 'Victoria Falls', country: 'Zimbawe', continent: 'Africa'},
	{id: 84, name: 'Table Mountain', country: 'South Africa', continent: 'Africa'},
	{id: 85, name: 'Mount Kilimanjaro', country: 'Tanzania', continent: 'Africa'},
	{id: 86, name: 'Djemaa el-Fna', country: 'Morocco', continent: 'Africa'},
	{id: 87, name: 'The Sphinx', country: 'Egypt', continent: 'Africa'},
	{id: 88, name: 'Great Mosque of Djenné', country: 'Mali', continent: 'Africa'},
	{id: 89, name: 'The Blue Nile Falls', country: 'Ethiopia', continent: 'Africa'},
	{id: 90, name: 'Colossi of Memnon', country: 'South Africa', continent: 'Africa'},
	{id: 91, name: 'The Valley of the Kings', country: 'Egypt', continent: 'Africa'},
	{id: 92, name: 'The Rock-Hewn Churches of Lalibela', country: 'Ethiopia', continent: 'Africa'},
	{id: 93, name: 'The Cape of Good Hope', country: 'South Africa', continent: 'Africa'},
	{id: 94, name: 'Sydney Opera House', country: 'Australia', continent: 'Oceania'},
	{id: 95, name: 'Uluru/Ayers Rock', country: 'Australia', continent: 'Oceania'},
	{id: 96, name: 'Great Barrier Reef', country: 'Australia', continent: 'Oceania'},
	{id: 97, name: 'Mount Cook', country: 'New Zealand', continent: 'Oceania'},
	{id: 98, name: 'Milford Sound', country: 'New Zealand', continent: 'Oceania'},
	{id: 99, name: 'Sky Tower', country: 'New Zealand', continent: 'Oceania'},
	{id: 100, name: 'Bungle Bungle Range', country: 'Australia', continent: 'Oceania'},
	{id: 101, name: 'The Twelve Apostles', country: 'Australia', continent: 'Oceania'},
	{id: 102, name: 'Franz Josef Glacier', country: 'New Zealand', continent: 'Oceania'},
	{id: 103, name: 'The Waitomo Glowworm Caves', country: 'New Zealand', continent: 'Oceania'},
	{id: 104, name: 'Mount Fuji', country: 'Japan', continent: 'Asia'},
	{id: 105, name: 'London Eye', country: 'United Kingdom', continent: 'Europe'},
	{id: 106, name: 'Notre Dame', country: 'France', continent: 'Europe'},
	{id: 107, name: 'Karnak Temple', country: 'Egypt', continent: 'Africa'},
	{id: 108, name: 'Capitol Hill', country: 'United States', continent: 'North America'},
	{id: 109, name: 'Brooklyn Bridge', country: 'United States', continent: 'North America'},
	{id: 110, name: 'Florence Cathedral', country: 'Italy', continent: 'Europe'},
	{id: 111, name: 'Matterhorn', country: 'Italy', continent: 'Europe'},
	{id: 112, name: 'Etna', country: 'Italy', continent: 'Europe'},
	{id: 113, name: 'White Cliffs of Dover', country: 'United Kingdom', continent: 'Europe'},
	{id: 114, name: 'Temple of Luxor', country: 'Egypt', continent: 'Africa'},
	{id: 115, name: 'Potala Palace', country: 'China', continent: 'Asia'},
	{id: 116, name: 'Hagia Sophia', country: 'Turkey', continent: 'Asia'},
	{id: 117, name: 'Yellowstone National Park', country: 'United States', continent: 'North America'},
	{id: 118, name: 'Sydney Harbor Bridge', country: 'Australia', continent: 'Oceania'},
	{id: 119, name: 'Pompidue Center', country: 'France', continent: 'Europe'},
	{id: 120, name: 'Mills in Kinderdijk', country: 'Netherlands', continent: 'Europe'},
	{id: 121, name: 'Helsinki Cathedral', country: 'Finland', continent: 'Europe'},
	{id: 122, name: 'Giant\'s Causeway', country: 'United Kingdom', continent: 'Europe'},
	{id: 123, name: 'Bran Castle', country: 'Romania', continent: 'Europe'},
	{id: 124, name: 'Abu Simbel', country: 'Egypt', continent: 'Africa'},
	{id: 125, name: 'Mausoleums in Timbuktu', country: 'Mali', continent: 'Africa'},
	{id: 126, name: 'Lion\'s Gate at Mycenae', country: 'Greece', continent: 'Europe'},
	{id: 127, name: 'Meteora\'s Monasteries', country: 'Greece', continent: 'Europe'},
	{id: 128, name: 'Shibuya Crossing', country: 'Japan', continent: 'Asia'},
	{id: 129, name: 'Chocolate Hills', country: 'Philippines', continent: 'Asia'},
	{id: 130, name: 'Zhangye Danxia National Park', country: 'China', continent: 'Asia'},
	{id: 131, name: 'Ha Long Bay', country: 'Vietnam', continent: 'Asia'},
	{id: 132, name: 'The Grand Palace', country: 'Thailand', continent: 'Asia'},
	{id: 133, name: 'Gyeongbokgung Palace', country: 'South Korea', continent: 'Asia'},
	{id: 134, name: 'Angel Falls', country: 'Venezuela', continent: 'South America'},
	{id: 135, name: 'Meenakshi Temple', country: 'India', continent: 'Asia'},
	{id: 136, name: 'Aachen Cathedral', country: 'Germany', continent: 'Europe'},
	{id: 137, name: 'Golden Temple', country: 'India', continent: 'Asia'},
	{id: 138, name: 'Brihadisvara Temple in Thanjavur', country: 'India', continent: 'Asia'},
	{id: 139, name: 'Statue of Unity', country: 'India', continent: 'Asia'},
	{id: 140, name: 'Hungarian Parliament Building', country: 'Hungary', continent: 'Europe'},
	{id: 141, name: 'Wat Phra Dhammakaya Temple', country: 'Thailand', continent: 'Asia'},
	{id: 142, name: 'Cologne Cathedral', country: 'Germany', continent: 'Europe'},
	{id: 143, name: 'Frauenkirche in Dresden', country: 'Germany', continent: 'Europe'},
	{id: 144, name: 'Lotus Temple', country: 'India', continent: 'Asia'},
	{id: 145, name: 'Belem Tower', country: 'Portugal', continent: 'Europe'},
	{id: 146, name: 'Palacio da Pena', country: 'Portugal', continent: 'Europe'},
	{id: 147, name: 'Giralda', country: 'Spain', continent: 'Europe'},
	{id: 148, name: 'Mosque of Cordoba', country: 'Spain', continent: 'Europe'},
	{id: 149, name: 'Arts and Sciences City', country: 'Spain', continent: 'Europe'},
	{id: 150, name: 'Cathedral of Santiago', country: 'Spain', continent: 'Europe'},
	{id: 151, name: 'El Escorial', country: 'Spain', continent: 'Europe'},
	{id: 152, name: 'Chambord Castle', country: 'France', continent: 'Europe'},
	{id: 153, name: 'Carcassonne', country: 'France', continent: 'Europe'},
	{id: 154, name: 'Grande Place', country: 'Belgium', continent: 'Europe'},
	{id: 155, name: 'Manneken Pis', country: 'Belgium', continent: 'Europe'},
	{id: 156, name: 'Rijksmuseum', country: 'Netherlands', continent: 'Europe'},
	{id: 157, name: 'Tower of London', country: 'United Kingdom', continent: 'Europe'},
	{id: 158, name: 'Schönbrunn Palace', country: 'Austria', continent: 'Europe'},
	{id: 159, name: 'Pompey & Vesubius', country: 'Italy', continent: 'Europe'},
	{id: 160, name: 'Diocletian Palace', country: 'Croatia', continent: 'Europe'},
	{id: 161, name: 'Dubrovnik walls', country: 'Croatia', continent: 'Europe'},
	{id: 162, name: 'Auschwiz', country: 'Poland', continent: 'Europe'},
	{id: 163, name: 'Winter Palace', country: 'Russia', continent: 'Europe'},
	{id: 164, name: 'Kremlin', country: 'Russia', continent: 'Europe'},
	{id: 165, name: 'Little Mermaid', country: 'Denmark', continent: 'Europe'},
	{id: 166, name: 'Turning Torso ', country: 'Sweden', continent: 'Europe'},
	{id: 167, name: 'Palmyra', country: 'Syria', continent: 'Asia'},
	{id: 168, name: 'Dead sea', country: 'Israel', continent: 'Asia'},
	{id: 169, name: 'Masada', country: 'Israel', continent: 'Asia'},
	{id: 170, name: 'Dome of the Rock', country: 'Palestine', continent: 'Asia'},
	{id: 171, name: 'Western wall', country: 'Israel', continent: 'Asia'},
	{id: 172, name: 'Qibla', country: 'Saudi Arabia', continent: 'Asia'},
	{id: 173, name: 'Sheikh Zayed Mosque', country: 'UAE', continent: 'Asia'},
	{id: 174, name: 'Ait Ben Haddou', country: 'Morocco', continent: 'Africa'},
	{id: 175, name: 'Hassan II Mosque', country: 'Morocco', continent: 'Africa'},
	{id: 176, name: 'Leptis Magna', country: 'Libya', continent: 'Africa'},
	{id: 177, name: 'Himeji Castle ', country: 'Japan', continent: 'Asia'},
	{id: 178, name: 'Genghis Khan Statue', country: 'Mongolia', continent: 'Asia'},
	{id: 179, name: 'Ulun Danu ', country: 'Indonesia', continent: 'Asia'},
	{id: 180, name: 'Hobbiton', country: 'New Zealand ', continent: 'Oceania'},
	{id: 181, name: 'Washington Monument', country: 'United States', continent: 'North America'},
	{id: 182, name: 'Lincoln Memorial', country: 'United States', continent: 'North America'},
	{id: 183, name: 'Pentagon', country: 'United States', continent: 'North America'},
	{id: 184, name: 'Bellagio Fountains', country: 'United States', continent: 'North America'},
	{id: 185, name: 'Disneyland', country: 'United States', continent: 'North America'},
	{id: 186, name: 'Gateway Arch', country: 'United States', continent: 'North America'},
	{id: 187, name: 'Monument Valley', country: 'United States', continent: 'North America'},
	{id: 188, name: 'Space Needle', country: 'United States', continent: 'North America'},
	{id: 189, name: 'Metropolitan Cathedral', country: 'Mexico', continent: 'North America'},
	{id: 190, name: 'Capitol in La Habana', country: 'Cuba', continent: 'North America'},
	{id: 191, name: 'Lima Cathedral', country: 'Peru', continent: 'South America'},
	{id: 192, name: 'Brasilia Cathedral', country: 'Brazil', continent: 'South America'},
	{id: 193, name: 'Octavio Frias de Oliveira Bridge', country: 'Brazil', continent: 'South America'},
	{id: 194, name: 'Maracana Stadium', country: 'Brazil', continent: 'South America'}
];